---
title: "806 Final Project"
author: "Emma Kinerson"
format: html
editor: visual
---

Paper Idea: Using data from undergraduate student in the lab. Exploring the role of seasonal microbes on plant growth. Looking to analyze data from frond optical density under the different experimental conditions.

Introduction:


Methods:

1.  Microbe Collection:

    Microbes were sampled from two different locations across all four seasons. Seven sample collections were completed at the La Roche sample site, and eight sample collections were completed at the Thompson Farm site. Samples were collected at the edge of a body of water using sterilized metal spatulas . Collection tubes were rinsed in the body of water three times before being used to collect duckweed and the surrounding water.

2.  Duckweed Line:

    Isogenic duckweed lines were created using duckweed from each respective site. Single fronds from each site were placed into twenty four well plates and allowed to asexually reproduce. From these two lines, axenic cultures were created for each respective line. These cultures were created by sterilizing the duckweed using a 1% bleach solution for one minute and thirty seconds. Following the bleach sterilization, the plants were rinsed three times with sterile water. The first rinse lasted forty five seconds with the following two rinses lasting ten minutes each. The sterile duckweed was then placed into sterile Krazčič media (K media) for each respective isogenic line. The duckweed within each new axenic culture were then plated on sterile enriched yeast mannitol media to test for microbe growth to ensure sterilization.

3.  Culturing Microbes:

    Duckweed from the microbe samples were crushed on the inside cover of a plate that contained yeast mannitol agarose using a sterilized inoculation loop. This inoculation loop was then used to streak the plate to culture the microbes from the duckweed. These plates were then incubated until colony growth was sufficient. Once sufficient growth was achieved, they were stored in a 4ºC refrigerator until use. 


4.  Experiment Design and Set Up:

    Both axenic duckweed lines were inoculated with each seasonal collection of microbes from both duckweed lines respective sample site. These inoculations were set up with 4 blocks containing 8 replicates each into six 96 well plates according to a randomized blocking map. This allowed for 32 replicates for each treatment. 
    To create the experimental inocula from the microbe samples, 15 mL culture tubes containing sterile yeast mannitol media were inoculated by swabbing with microbes from each combination of site and date. The experimental combinations of these microbes were cultured for two days at an RPM of 300 and at 30ºC. A BioTek Cytation 5 Plate Reader was used to examine optical density at 600 nm for each microbe inocula to test cell concentration. Cell concentrations from the OD readings wree used to dilute all inocula to the same concentration (5000 cells/µl). Dilutions were formed by adding a calculated amount of microbe inocula to sterile Hogland's media in the laminar flow hood. 
    Well plates were prepped by placing 600 µl of sterilized Hogland's media into each well, followed by placing duckweed fronds in each well. A seal (BreathEasier Diversified Biotech) was placed onto each plate and then the plates were left in the sterile laminar flow hood overnight. 
    Each microbe inocula (10 µl) were added to the 96 well plates according to the randomized block design. This was completed by puncturing through the Breatheasier seal. Once all wells were inoculated, the BreathEasier seal was removed and a new seal (BreathEasy Diversified Biotech) was placed onto the plate to prevent contamination. 
    Plates were placed into the growth chamber and imaged on day 12. Images were taken using an iPhone 13 cell phone camera. Images were taken through the plexiglass shield that the plate were set upon to ensure uniform images. ImageJ was used for analysis to measure duckweed growth. 


5.  Statistical Tests:
